name:                stockquotes
version:             0.1.0.0
github:              "githubuser/stockquotes"
license:             BSD3
author:              "Mairead Meagher based on Vitaly Bragilevsky"
maintainer:          "mmeagher@wit.ie"
copyright:           "2021 Based on Haskell In Depth, Vitaly Bragilevsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stockquotes#readme>

dependencies:
- base >= 4.7 && < 5
- time >=1.8 && <1.12
- text >=1.2 && <1.3
- csv


library:
  source-dirs: src
  exposed-modules: 
    - CleanData
    - QuoteData
    - StatReport
  dependencies: 
    - split
    - sort
    - unique
executables:
  stockquotes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N      
    dependencies: 
    - stockquotes

tests:
  stockquotes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stockquotes
