name:                stockex
version:             0.1.0.0
github:              "githubuser/stockex"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stockex#readme>

dependencies:
- base >= 4.7 && < 5


library:
  source-dirs: src
  dependencies : 
  - optparse-applicative
  - time
  - safe
  - bytestring
  - cassava
  - Chart
  - Chart-diagrams 
  - text 
  - blaze-html
  - fmt

executables:
  stockex-exe:
    main:                Main.hs
    source-dirs:         app
    other-extensions:
      - RecordWildCards
      - OverloadedStrings
      - FlexibleInstances
      - DeriveGeneric
      - DeriveAnyClass
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stockex
    - cassava
tests:
  stockex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stockex
